language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
matrix:
  include:
    - # Ruby 1.9
      rvm: 1.9
      env: JEKYLL_VERSION=2.0
env:
  matrix:
    - JEKYLL_VERSION=3.0
    - JEKYLL_VERSION=2.0
script: "./script/cibuild"
